config/routes.rb
Rails.application.routes.draw do
    resources :vouchers do
       resources :voucher_entries, only: [:index, :new, :create, :destroy]
    end    
  resources :contracts
  root "home#index"
  resources :contractors
  resources :projects
  resources :clients
  resources :accounts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
 resources :accounts
  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/contractor.rb
class Contractor < ApplicationRecord
  belongs_to :account
  has_many :contracts
  has_many :projects, through: :contracts
end

app/controllers/contractors_controller.rb
class ContractorsController < ApplicationController
  before_action :set_contractor, only: %i[ show edit update destroy ]

  # GET /contractors or /contractors.json
  def index
    @contractors = Contractor.all
  end

  # GET /contractors/1 or /contractors/1.json
  def show
  end

  # GET /contractors/new
  def new
    @contractor = Contractor.new
  end

  # GET /contractors/1/edit
  def edit
  end

  # POST /contractors or /contractors.json
  def create
    @contractor = Contractor.new(contractor_params)

    respond_to do |format|
      if @contractor.save
        format.html { redirect_to @contractor, notice: "Contractor was successfully created." }
        format.json { render :show, status: :created, location: @contractor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contractor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contractors/1 or /contractors/1.json
  def update
    respond_to do |format|
      if @contractor.update(contractor_params)
        format.html { redirect_to @contractor, notice: "Contractor was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @contractor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contractor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contractors/1 or /contractors/1.json
  def destroy
    @contractor.destroy!

    respond_to do |format|
      format.html { redirect_to contractors_path, notice: "Contractor was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contractor
      @contractor = Contractor.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def contractor_params
      params.expect(contractor: [ :name, :contractor_type, :specialization, :phone, :email, :account_id ])
    end
end

app/helpers/contractors_helper.rb
module ContractorsHelper
end

app/views/contractors/_contractor.html.erb
<div id="<%= dom_id contractor %>">
  <p>
    <strong>Name:</strong>
    <%= contractor.name %>
  </p>

  <p>
    <strong>Contractor type:</strong>
    <%= contractor.contractor_type %>
  </p>

  <p>
    <strong>Specialization:</strong>
    <%= contractor.specialization %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= contractor.phone %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= contractor.email %>
  </p>

  <p>
    <strong>Account:</strong>
    <%= contractor.account_id %>
  </p>

</div>

app/views/contractors/_form.html.erb
<%= form_with(model: contractor) do |form| %>
  <% if contractor.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(contractor.errors.count, "error") %> prohibited this contractor from being saved:</h2>

      <ul>
        <% contractor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

<div class="field">
  <%= form.label :contractor_type %>
  <%= form.select :contractor_type, 
        options_for_select(["Petty Contractor", "Main Contractor", "Sub Contractor"], @contractor.contractor_type), 
        {}, 
        { class: "form-control" } %>
</div>


  <div>
    <%= form.label :specialization, style: "display: block" %>
    <%= form.text_field :specialization,  placeholder: "e.g. Civil, Plumbing, Electrical"%>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

<div class="field">
  <%= form.label :account_id, "Account" %>
  <%= form.collection_select :account_id, Account.all, :id, :name, { prompt: "Select Account" }, class: "form-control" %>
</div>


  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/contractors/edit.html.erb
<% content_for :title, "Editing contractor" %>

<h1>Editing contractor</h1>

<%= render "form", contractor: @contractor %>

<br>

<div>
  <%= link_to "Show this contractor", @contractor %> |
  <%= link_to "Back to contractors", contractors_path %>
</div>

app/views/contractors/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Contractors" %>

<h1>Contractors</h1>

<div id="contractors">
  <% @contractors.each do |contractor| %>
    <%= render contractor %>
    <p>
      <%= link_to "Show this contractor", contractor %>
    </p>
  <% end %>
</div>

<%= link_to "New contractor", new_contractor_path %>

app/views/contractors/new.html.erb
<% content_for :title, "New contractor" %>

<h1>New contractor</h1>

<%= render "form", contractor: @contractor %>

<br>

<div>
  <%= link_to "Back to contractors", contractors_path %>
</div>

app/views/contractors/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @contractor %>

<div>
  <%= link_to "Edit this contractor", edit_contractor_path(@contractor) %> |
  <%= link_to "Back to contractors", contractors_path %>

  <%= button_to "Destroy this contractor", @contractor, method: :delete %>
</div>