config/routes.rb
Rails.application.routes.draw do
    resources :vouchers do
       resources :voucher_entries, only: [:index, :new, :create, :destroy]
    end    
  resources :contracts
  root "home#index"
  resources :contractors
  resources :projects
  resources :clients
  resources :accounts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
 resources :accounts
  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/voucher_entry.rb
class VoucherEntry < ApplicationRecord
  belongs_to :voucher
  belongs_to :account

  validates  :entry_type, presence: true, inclusion: {in: ['debit', 'credit']}
  validates :amount, presence: true, numericality: {greater_than: 0}
end

app/controllers/voucher_entries_controller.rb
class VoucherEntriesController < ApplicationController
  before_action :set_voucher_entry, only: %i[ show edit update destroy ]

  # GET /voucher_entries or /voucher_entries.json
  def index
    @voucher_entries = VoucherEntry.all
  end

  # GET /voucher_entries/1 or /voucher_entries/1.json
  def show
  end

  # GET /voucher_entries/new
  def new
    @voucher_entry = VoucherEntry.new
  end

  # GET /voucher_entries/1/edit
  def edit
  end

  # POST /voucher_entries or /voucher_entries.json
  def create
    @voucher_entry = VoucherEntry.new(voucher_entry_params)

    respond_to do |format|
      if @voucher_entry.save
        format.html { redirect_to @voucher_entry, notice: "Voucher entry was successfully created." }
        format.json { render :show, status: :created, location: @voucher_entry }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @voucher_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /voucher_entries/1 or /voucher_entries/1.json
  def update
    respond_to do |format|
      if @voucher_entry.update(voucher_entry_params)
        format.html { redirect_to @voucher_entry, notice: "Voucher entry was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @voucher_entry }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @voucher_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /voucher_entries/1 or /voucher_entries/1.json
  def destroy
    @voucher_entry.destroy!

    respond_to do |format|
      format.html { redirect_to voucher_entries_path, notice: "Voucher entry was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_voucher_entry
      @voucher_entry = VoucherEntry.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def voucher_entry_params
      params.expect(voucher_entry: [ :voucher_id, :account_id, :debit, :credit, :narration ])
    end
end

app/helpers/voucher_entries_helper.rb
module VoucherEntriesHelper
end

app/views/voucher_entries/_form.html.erb
<%= form_with(model: voucher_entry) do |form| %>
  <% if voucher_entry.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(voucher_entry.errors.count, "error") %> prohibited this voucher_entry from being saved:</h2>

      <ul>
        <% voucher_entry.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :voucher_id, style: "display: block" %>
    <%= form.text_field :voucher_id %>
  </div>

  <div>
    <%= form.label :account_id, style: "display: block" %>
    <%= form.text_field :account_id %>
  </div>

  <div>
    <%= form.label :debit, style: "display: block" %>
    <%= form.text_field :debit %>
  </div>

  <div>
    <%= form.label :credit, style: "display: block" %>
    <%= form.text_field :credit %>
  </div>

  <div>
    <%= form.label :narration, style: "display: block" %>
    <%= form.text_field :narration %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/voucher_entries/_voucher_entry.html.erb
<div id="<%= dom_id voucher_entry %>">
  <p>
    <strong>Voucher:</strong>
    <%= voucher_entry.voucher_id %>
  </p>

  <p>
    <strong>Account:</strong>
    <%= voucher_entry.account_id %>
  </p>

  <p>
    <strong>Debit:</strong>
    <%= voucher_entry.debit %>
  </p>

  <p>
    <strong>Credit:</strong>
    <%= voucher_entry.credit %>
  </p>

  <p>
    <strong>Narration:</strong>
    <%= voucher_entry.narration %>
  </p>

</div>

app/views/voucher_entries/edit.html.erb
<% content_for :title, "Editing voucher entry" %>

<h1>Editing voucher entry</h1>

<%= render "form", voucher_entry: @voucher_entry %>

<br>

<div>
  <%= link_to "Show this voucher entry", @voucher_entry %> |
  <%= link_to "Back to voucher entries", voucher_entries_path %>
</div>

app/views/voucher_entries/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Voucher entries" %>

<h1>Voucher entries</h1>

<div id="voucher_entries">
  <% @voucher_entries.each do |voucher_entry| %>
    <%= render voucher_entry %>
    <p>
      <%= link_to "Show this voucher entry", voucher_entry %>
    </p>
  <% end %>
</div>

<%= link_to "New voucher entry", new_voucher_entry_path %>

app/views/voucher_entries/new.html.erb
<% content_for :title, "New voucher entry" %>

<h1>New voucher entry</h1>

<%= render "form", voucher_entry: @voucher_entry %>

<br>

<div>
  <%= link_to "Back to voucher entries", voucher_entries_path %>
</div>

app/views/voucher_entries/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @voucher_entry %>

<div>
  <%= link_to "Edit this voucher entry", edit_voucher_entry_path(@voucher_entry) %> |
  <%= link_to "Back to voucher entries", voucher_entries_path %>

  <%= button_to "Destroy this voucher entry", @voucher_entry, method: :delete %>
</div>